// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

declare namespace NodeJS {
  interface ProcessEnv {
    NEYNAR_API_KEY: string;
    CLOUDFLARE_KV_NAMESPACE_ID: string;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_API_TOKEN: string;
    NEXT_PUBLIC_API_URL: string;
    NODE_ENV: 'development' | 'production' | 'test';
  }
}

interface CloudflareEnv {
  NEYNAR_API_KEY: string;
  CLOUDFLARE_KV_NAMESPACE_ID: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_TOKEN: string;
  NEXT_PUBLIC_API_URL: string;
  NODE_ENV: 'development' | 'production' | 'test';

}
